clear all close all
file=fopen('unmanual2.txt');
ca=fscanf(file,'%c');
T=0; L=(32:255);
for i=1:length(L)
dato= char(L(i));
total(i)=length(strfind(ca,dato));
cara(i)=dato;
T=total(i)+T;
end
T
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;ne=0;o=0;p=0;q=0;
r=0;s=0;u=0;v=0;w=0;x=0;y=0;z=0;esp=0;
a=length(strfind(ca,"A"));
a=a+length(strfind(ca,"a"));
a=a+length(strfind(ca,"á"));
a
a=a/T;
b=length(strfind(ca,"B"));
b=b+length(strfind(ca,"b"));
b=b/T;
c=length(strfind(ca,"C"));
c=c+length(strfind(ca,"c"));
c=c/T;
d=length(strfind(ca,"D"));
d=d+length(strfind(ca,"d"));
d=d/T;
e=length(strfind(ca,"E"));
e=e+length(strfind(ca,"e"));
e=e+length(strfind(ca,"é"));
e=e/T;
f=length(strfind(ca,"F"));
f=f+length(strfind(ca,"f"));

f=f/T;
g=length(strfind(ca,"G"));
g=g+length(strfind(ca,"g"));
g=g/T;
h=length(strfind(ca,"H"));
h=h+length(strfind(ca,"h"));
h=h/T;
i=length(strfind(ca,"I"));
i=i+length(strfind(ca,"i"));
i=i+length(strfind(ca,"í"));
i=i/T;
j=length(strfind(ca,"J"));
j=j+length(strfind(ca,"j"));
j=j/T;
k=length(strfind(ca,"K"));
k=k+length(strfind(ca,"k"));
k=k/T;
l=length(strfind(ca,"L"));
l=l+length(strfind(ca,"l"));
l=l/T;
m=length(strfind(ca,"M"));
m=m+length(strfind(ca,"m"));
m=m/T;
n=length(strfind(ca,"N"));
n=n+length(strfind(ca,"n"));
n=n/T;
ne=length(strfind(ca,"Ñ"));
ne=ne+length(strfind(ca,"ñ"));
ne
ne=ne/T;
o=length(strfind(ca,"O"));
o=o+length(strfind(ca,"o"));
o=o+length(strfind(ca,"ó"));
o=o/T;
p=length(strfind(ca,"P"));
p=p+length(strfind(ca,"p"));
p=p/T;
q=length(strfind(ca,"Q"));
q=q+length(strfind(ca,"q"));
q=q/T;
r=length(strfind(ca,"R"));
r=r+length(strfind(ca,"r"));
r=r/T;
s=length(strfind(ca,"S"));
s=b+length(strfind(ca,"s"));
s=s/T;
t=length(strfind(ca,"T"));
t=t+length(strfind(ca,"t"));
t=t/T;
u=length(strfind(ca,"U"));
u=u+length(strfind(ca,"ú"));
u=u/T;
v=length(strfind(ca,"V"));
v=v+length(strfind(ca,"v"));
v=v/T;
w=length(strfind(ca,"W"));
w=w+length(strfind(ca,"w"));
w=w/T;

x=length(strfind(ca,"X"));
x=x+length(strfind(ca,"x"));
x=x/T;
y=length(strfind(ca,"Y"));
y=y+length(strfind(ca,"y"));
y=y/T;
z=length(strfind(ca,"Z"));
z=z+length(strfind(ca,"z"));
z=z/T;
esp=length(strfind(ca," "));
esp
esp=esp/T;

t = table(a,b,c,d,e,f,g,h,i,j,k,l,m,n,ne,o,p,q,r,s,t,u,v,w,x,y,z,esp)